### ISSUE TITLE
求截图

### ISSUE THREAD

**Issue by Nokecy** [HuangXingBin/goldenEast#2]

**Comment by HuangXingBin** [comment]
等我用meteor.js搞定全栈先，这两个月的事

**Comment by Nokecy** [comment]
我来帮你做呀~~ 教教我呀 我很聪明的

**Comment by HuangXingBin** [comment]
有个php太水 我在考虑要不要接过他的工作
我用的是react-webpack-babel这个github开源的webpack配置，加上redux, react-router,没了。
